language: python
python:
  - "3.5"

# command to run tests
script:
  - "python Tests/CompilerTests/default_compiler_unittest.py"
  - "python Tests/ModuleTests/links_module_unit_tests.py"
  - "python Tests/CompilerTests/compiler_unittests.py"
